#!/bin/bash
set -e # Any subsequent(*) commands which fail will cause the shell script to exit immediately

cd "$(dirname $0)/.."

echo -e "Bootstrapping..."

if [ "$OSTYPE" != "linux-gnu" ]
then
    echo "Unsupported OS. Only works on Ubuntu. Sry, kiss"
    exit 1
fi

echo -e "\nInstalling NodeJS, npm, git..."
sudo apt-get update
sudo apt-get install -y curl
curl -sL https://deb.nodesource.com/setup | sudo bash - # Install PPA maintained by NodeSource
sudo apt-get install -y 'nodejs=0.10.*' git libfreetype6 libfontconfig
sudo npm install -g npm@2.7.*
which node >/dev/null || sudo ln -s /usr/bin/nodejs /usr/bin/node

echo -e "\nInstalling Bower"
sudo npm install -g bower@1.3.*

echo -e "\nInstalling repository depencies"
npm install
bower --allow-root install

echo "\nInstalled node $(node -v), npm v$(npm -v) and bower v$(bower -v)"

echo "SUCCESS"
exit 0
