#!/bin/bash
set -e # Any subsequent(*) commands which fail will cause the shell script to exit immediately

cd "$(dirname $0)/.."

echo -e "Linting..."
./node_modules/.bin/eslint --ext .jsx --ext .js .

echo "SUCCESS"
exit 0
