#!/bin/bash
set -e # Any subsequent(*) commands which fail will cause the shell script to exit immediately

cd "$(dirname $0)/.."

echo -e "Checking the syntax..."
npm run lint

echo "SUCCESS"
exit 0
